apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::950554973694:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K24L2O1Y6O2J
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::950554973694:role/UdacityFlaskDeployCBKubectlRole
      username: build    
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-14T00:37:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1655"
  uid: eda153f5-d403-47ca-acdd-6c22110c83a2
